
name: CI
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Secrets action
    env:
      MATTMONGOCONNECT: ${{ secrets.MATTMONGOCONNECT }}

